### ISSUE TITLE
Option to hide all images and their captions?

### ISSUE THREAD

**Issue by thefferon** [ushnisha/tranquility-reader-webextensions#32] opened 2021-07-30 18:28 UTC
I use Tranquility mainly to copy the text of articles I want to read, which I then paste into a Word document which I have pre-formatted for layout and readability. 99 times out of 100 I do not want to include images and their captions in the final version of the Word doc (which I may print on paper or save as a pdf).

Please enable a setting / option within Tranquility whereby I can completely eliminate all images and their captions from the Tranquility display.

Thank you!

**Comment by ushnisha** [comment] 2021-08-02 06:27
Agree - this is a good option to have.  Will add an option as requested in the next release.

**Comment by ushnisha** [comment] 2021-08-23 09:14
Version (3.0.23) has been submitted for review with changes to handle this issue.

A new option is available in the extension preferences/options:

A drop-down option labeled "Hide Images" can be configured to one of the following values:

"never":  This is the default value and continues the current behavior of displaying images whenever possible
"always": This option will always hide all images both in the transformed page as well as the PDF printed using this extension
"hide_only_for_print":  This option will display images on the transformed page whenever possible, but will hide them in the PDF printed using this extension.

Image captions may not always be successfully hidden; this depends on how the image caption is specified in the underlying html document.  If the author of the page uses suitable encapsulating tags like FIGCAPTION or FIGURE or PICTURE, then caption may also be hidden.  Otherwise, some of the image captions will still be displayed/printed.

Please test this out once 3.0.23 is officially approved/released.  Since there is a lengthy queue for review this could take a few days or even weeks (depending on how the review is prioritized/queued).

**Comment by ushnisha** [comment] 2021-08-31 05:07
3.0.23 is now released.  The option is working as designed in the released version.  Closing this issue now.

**Closed as completed by ushnisha** 2021-08-31 05:07 UTC
Labels: enhancement
