### ISSUE TITLE
Version 3.0.25 doesn't work as expected

### ISSUE THREAD

**Issue by DenB10** [ushnisha/tranquility-reader-webextensions#49] opened 2024-06-03 18:08 UTC
@ushnisha 

Hi Arun,

After installing version 3.0.25 on top of 3.0.24, I noticed malfunctions with the context menu and the "View", "Export" and "Import" functions on the options page.
I then uninstalled and reinstalled version 3.0.25, and now there's no context menu at all. I can tranquilize a page via the toolbar button, all the internal buttons work, but of course I can't add annotations, nor can I view, export or import offline content via the options page.

I'm running Firefox 115 ESR on Windows 7 64-bit. Is this a Win7 problem or a FF 115 problem? Is the minimum version (109.0) to use this version of Tranquility correct?
I should point out that deactivating all my other add-ons doesn't help.

Can you reproduce?

Best regards,

DenB

**Comment by ushnisha** [comment] 2024-06-04 05:32
I am able to reproduce.

The minimum required version cannot be lower than 109 because I updated the extension to use the new manifest v3 specifications.

When I made the changes to conform to manifest v3, the changes looked trivial enough.  But I suspect that I have not understood all of the implications of those changes and they may have broken some functionality.

I will look into it in more detail and update this issue.

**Comment by ushnisha** [comment] 2024-06-09 09:07
DenB10,

Thanks again for opening the issue and my sincere apologies -- I clearly missed testing thoroughly when upgrading to manifest v3.

I am finding it challenging to figure out where the update is breaking in Manifest v3.  This make take a while and it is not even clear to me if this is a manifest v3 limitation in Firefox, or something that I am not doing properly (since some of this functionality works fine with similar manifest v3 changes in Chrome in my testing).

So, I have reversed my changes back to Manifest v2 and will submit an new version in the next couple of days.  My testing so far indicates, that the issues you have pointed out are working as expected after reverting to manifest v2.  I will test some more and submit.

**Comment by ushnisha** [comment] 2024-06-12 04:12
version 3.0.26 has been approved on June 11; I have reverted back to manifest v2 and the extension should work as before and all of the issues you have highlighted should be fixed.

**Comment by DenB10** [comment] 2024-06-12 19:48
@ushnisha 

This new version works well except for one strange thing: 
If you try to import offline content from the options page when it's the only tab open (Add-ons Manager), Firefox closes immediately. You need to have another tab open to be able to import.
It seems that this behavior already existed in version 3.0.24, unless it's an internal problem with my FF config?

Can you confirm?

**Comment by ushnisha** [comment] 2024-06-13 10:32
I am able to reproduce this bug too -- you are correct this problem existed in 3.0.24 (and very likely in earlier versions too).  I will add a fix for this in the next release.  

As you have observed, having at least one other tab open when exporting or importing the saved/offline content to prevent firefox from closing.

When exporting/importing offline content, a new tab is opened and my code is trying to close this new tab after completing the export/import -- but the bug is that it is closing the current tab (before the export/import code has executed).  And if there is only a single tab open, default behavior of firefox is to exit the program.

I will open a new ticket for this new issue and close the current one as fixed.

**Comment by ushnisha** [comment] 2024-06-15 12:49
Closed as fixed in version 3.0.26.  Related issue will be addressed in #51.

**Closed as completed by ushnisha** 2024-06-15 12:49 UTC
Labels: bug
