### ISSUE TITLE
Offline links missing

### ISSUE THREAD

**Issue by DenB10** [ushnisha/tranquility-reader-webextensions#11] opened 2019-10-05 12:37 UTC
Hi,
I've updated Tranquility to the latest version (3.0.12) in FF 60.9.0 ESR.
I notice the offline links names have disappear, I can't click them, only delete.
Do you experience the same issue?
Thank you very much for your work.
DenB

**Comment by ushnisha** [comment] 2019-10-06 09:04
Hi DenB,

I am able to reproduce this problem for new links that I save to offline content; can you confirm that any older offline pages saved in earlier versions show the title properly?  That will help me make sure that the problem is not with the retreival mechanism, but with the saving of new offline links alone.  Thanks!

**Comment by DenB10** [comment] 2019-10-06 10:07
Oops! I forgot to mention this important point: yes, the previous offline page titles are shown properly in the list, only the new ones are missing.
I think the issue comes from the "removed hidden elements" in tranquilize.js file: when I comment the line `deleteHiddenElements(contentDoc, "*");`, everything is alright. I don't know if that helps!

**Comment by ushnisha** [comment] 2019-10-11 08:58
Hi DenB10,

Thanks for the comment.  I have a fix in the next version which is submitted and waiting for review/approval to publish.

In 3.0.11 and earlier versions, I was deleting a subset of hidden elements, but decided to expand that to all hidden elements.  Here, a hidden element is identified as an element for which either the css property of "visibility" set to "hidden" or css property of "display" set to "none".

Unfortunately, I did not realize that both the "HEAD" and "TITLE" elements are assigned a default "display" property of "none" by many browsers; I assumed that web page authors will always need to set these hidden properties explicitly.  I have now added an exception in the deleteHiddenElements function that prevents HEAD/TITLE tags from being deleted and that solves the problem.

Thanks again for your feedback!  I will wait for the release to get approved and then close this issue a few days after that.

**Comment by DenB10** [comment] 2019-10-11 09:20
OK, thank you very much!

**Comment by DenB10** [comment] 2019-10-11 17:33
I've tested the new version: all is OK now!

One suggestion though: there is currently no way to access directly the offline pages from the toolbar button. Is it possible to implement this feature? Thank you!

**Comment by ushnisha** [comment] 2019-10-12 06:44
DenB10,

Thanks for validating the fix.

> One suggestion though: there is currently no way to access directly the offline pages from the toolbar button. Is it possible to implement this feature? Thank you!

In the legacy version of the extension (using the older XUL technology) I provided such a feature; clicking on the button would transform the page, and you could add a small drop-down arrow to the right of the icon that would provide quick access to the preferences, reading offline pages, saving offline, export/import offline pages etc.

Unfortunately, when we had to move to webextensions framework, the browser_action feature did not support this -- you could either launch a background script (which is the current behavior to transform the page) or you could show a small "pop-up" with additional actions.  In fact, in my very first webextensions version, I provided such a pop-up; but several people complained that they were now forced to click twice -- once to open the pop-up and a second time to transform the page.

I got the impression that this was so user-unfriendly that it was better to do away with the "pop-up" and simply transform the page when the button is clicked.  So many of the other actions are accessed so infrequently that easier access to them did not justify making the most performed (and intuitive) function of the button display the pop-up.

I checked the documentation again; I don't think there is any change to this behavior; If you know of any other extension that is able to do something like the behavior you want, please do let me know and I'll inspect their code to figure out if I can do something similar for Tranquility Reader.  Thanks!

**Comment by DenB10** [comment] 2019-10-12 17:45
I don't understand why it's impossible to add a context menu item for the toolbar button which gives the ability to access to the offline content, since those pages seem to be locally stored (am I right?). A lot of Firefox add-ons I've installed offer such a functionality (e.g. Brief, Zoom Page, Skip Redirect, ...).

But no matter, it isn't so important, the main purpose of Tranquility Reader is to make pages readable and this is achieved very well ;)

Have a nice week-end!

**Comment by ushnisha** [comment] 2020-02-20 06:26
Fixed in 3.0.13; closing.

**Closed as completed by ushnisha** 2020-02-20 06:26 UTC
